name: {{cookiecutter.project_name}}
description: {{cookiecutter.project_description}}
author: {{cookiecutter.author}}
author_email: {{cookiecutter.author_email}}
license: {{cookiecutter.license}}
copyright: {{cookiecutter.copyright}}
modulepath: libs
downloadpath: libs
repo:
    - type: git
      url: {{cookiecutter.repo_url}}
    # Index url for V2 modules
    # This is for <=ISO6 (inmanta-core<=10)
    - type: package
      url: {{cookiecutter.package_repo_url}} 
pip: # for >=ISO7 (inmanta-core>=11)
  # Index url for python package and V2 modules
  index_url: {{cookiecutter.package_repo_url}}
  # Extra index urls for python package and V2 modules
  extra_index_url: []
  # Allow pip to install prerelease versions or not?
  pre: {{cookiecutter.install_mode != "release"}}
  # Use the pip system config or not?
  # May have security implications
  use_system_config: false
install_mode: {{cookiecutter.install_mode}}
requires:
pip:
    index_urls:
        - {{cookiecutter.package_repo_url}}
