name: {{cookiecutter.project_name}}
description: {{cookiecutter.project_description}}
author: {{cookiecutter.author}}
author_email: {{cookiecutter.author_email}}
license: {{cookiecutter.license}}
copyright: {{cookiecutter.copyright}}
modulepath: libs
downloadpath: libs
repo:
    - type: git
      url: {{cookiecutter.modules_v1_repo_url}}
install_mode: {{cookiecutter.install_mode}}
requires:
pip:
    index_url:
        - {{cookiecutter.pip_index_url}}
